"""Chapter briefs API endpoints for v6.9.0.

Provides endpoints for retrieving chapter briefs generated by the Planner.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from fastapi import APIRouter, Request, HTTPException

from ..envelope import envelope_response, error_response, EnvelopeResponse
from ...exceptions import APIValidationError
from ...db.repository import Repository

router = APIRouter()
logger = logging.getLogger(__name__)


# ── Helper Functions ──────────────────────────────────────────────────────


def _get_repo(request: Request) -> Repository:
    """Get repository from request state."""
    return request.state.repo


# ── Endpoints ─────────────────────────────────────────────────────────────


@router.get("/projects/{project_id}/chapters/{chapter_number}/brief")
async def get_chapter_brief(
    project_id: str,
    chapter_number: int,
    request: Request,
) -> EnvelopeResponse:
    """Get the chapter brief for a specific chapter.
    
    Returns the ChapterBrief JSON generated by the Planner agent.
    The brief contains Tier 1 (required) and Tier 2 (optional) fields
    that guide downstream agents (Screenwriter, Author, etc.).
    
    Args:
        project_id: Project identifier
        chapter_number: Chapter number (1-based)
        
    Returns:
        Chapter brief data or error if not found
    """
    repo = _get_repo(request)
    
    try:
        # Get the chapter
        chapter = repo.get_chapter(project_id, chapter_number)
        if not chapter:
            raise APIValidationError(
                "CHAPTER_NOT_FOUND",
                f"Chapter {chapter_number} not found for project {project_id}",
            )
        
        # Get the instruction for this chapter
        instruction = repo.get_instruction_by_chapter(project_id, chapter_number)
        if not instruction:
            return envelope_response({
                "project_id": project_id,
                "chapter_number": chapter_number,
                "chapter_brief": None,
                "source": "not_found",
                "note": "Chapter brief not generated yet. Run the planner first.",
            })
        
        # The instruction contains the planner output
        # In the current implementation, the instruction's objective field
        # contains the chapter goal, but we need to extract the full brief
        # For now, we'll construct a basic brief from the instruction fields
        chapter_brief = {
            "chapter_goal": instruction.get("objective", ""),
            "reader_payoff": instruction.get("ending_hook", ""),
            "protagonist_agency": instruction.get("emotion_tone", ""),
            "forbidden_moves": [],  # Not stored in current instruction format
            "pressure_budget": None,
            "payoff_budget": None,
            "upgrade_or_skill_use": None,
            "character_arc_moves": None,
            "mystery_actions": None,
            "conflict_actions": None,
            "ledger_debts_to_pay": [],
            "new_debts_allowed": True,
            "scene_count_target": None,
            "opening_hook": None,
            "ending_hook": instruction.get("ending_hook", ""),
            "quality_threshold_overrides": None,
        }
        
        return envelope_response({
            "project_id": project_id,
            "chapter_number": chapter_number,
            "chapter_brief": chapter_brief,
            "source": "instruction",
            "note": "Chapter brief derived from instruction. Full brief requires planner output.",
        })
        
    except APIValidationError as e:
        return error_response(e.code, e.message)
    except Exception as e:
        logger.error(f"Failed to get chapter brief: {e}")
        return error_response(
            "INTERNAL_ERROR",
            f"Failed to retrieve chapter brief: {str(e)}",
        )